baseURL: "https://samsm.ch"
title: Sam Smith

disablePathToLower: true
summaryLength: 999999999999

pagination:
  pagerSize: 10

params:
  author: Sam Smith
  dark_css: "css/dark.css"
  sitename: Sam Smith's Blog
  description: |
    My blog! I write about (mostly analog) photography and (mostly golang)
    programming

menu:
  main:
    - identifier: about
      name: About
      title: About
      url: /about/
      weight: 0

    - identifier: archive
      name: Archive
      url: /posts/
      weight: 1

  footer:
    - identifier: categories
      name: Categories
      title: Categories
      url: /categories/
      weight: 0

    - identifier: tags
      name: Tags
      title: Tags
      url: /tags/
      weight: 1

taxonomies:
  category: categories
  tag: tags

markup:
  highlight:
    style: trac
  goldmark:
    renderer:
      unsafe: true
    parser:
      attribute: true
      autoHeadingID: true
      autoHeadingIDType: github
  tableOfContents:
    ordered: true

languages:
  en:
    languageName: "English"
    languagecode: "en-gb"
    weight: 1
